DELETE FROM cs_class_attr WHERE class_id = (select id from cs_class where name like 'test2');
DELETE FROM cs_class_attr WHERE class_id = (select id from cs_class where name like 'test3');
DELETE FROM cs_class_attr WHERE class_id = (select id from cs_class where name like 'test4');
DELETE FROM cs_class_attr WHERE class_id = (select id from cs_class where name like 'test6');
DELETE FROM cs_attr where class_id = (select id from cs_class where name like 'test1');
DELETE FROM cs_attr where class_id = (select id from cs_class where name like 'test2');
DELETE FROM cs_attr where class_id = (select id from cs_class where name like 'test3');
DELETE FROM cs_attr where class_id = (select id from cs_class where name like 'test4');
DELETE FROM cs_attr where class_id = (select id from cs_class where name like 'test5');
DELETE FROM cs_attr where class_id = (select id from cs_class where name like 'test6');
DELETE FROM cs_type WHERE name LIKE 'test1';
DELETE FROM cs_type WHERE name LIKE 'test2';
DELETE FROM cs_type WHERE name LIKE 'test3';
DELETE FROM cs_type WHERE name LIKE 'test4';
DELETE FROM cs_type WHERE name LIKE 'test5';
DELETE FROM cs_type WHERE name LIKE 'test6';
DELETE FROM cs_class WHERE name LIKE 'test1';
DELETE FROM cs_class WHERE name LIKE 'test2';
DELETE FROM cs_class WHERE name LIKE 'test3';
DELETE FROM cs_class WHERE name LIKE 'test4';
DELETE FROM cs_class WHERE name LIKE 'test5';
DELETE FROM cs_class WHERE name LIKE 'test6';

INSERT INTO cs_class(name, class_icon_id, object_icon_id, table_name, primary_key_field, indexed, array_link)         VALUES ('test1', 1, 1, 'test1', 'ID', false, false);
INSERT INTO cs_class(name, class_icon_id, object_icon_id, table_name, primary_key_field, indexed, array_link)         VALUES ('test2', 1, 1, 'test2', 'ID', false, false);
INSERT INTO cs_class(name, class_icon_id, object_icon_id, table_name, primary_key_field, indexed, array_link, policy) VALUES ('test3', 1, 1, 'test3', 'ID', false, false, (select id from cs_policy where name like 'SECURE'));
INSERT INTO cs_class(name, class_icon_id, object_icon_id, table_name, primary_key_field, indexed, array_link)         VALUES ('test4', 1, 1, 'test4', 'ID', false, false);
INSERT INTO cs_class(name, class_icon_id, object_icon_id, table_name, primary_key_field, indexed, array_link)         VALUES ('test5', 1, 1, 'test5', 'ID', false, false);
INSERT INTO cs_class(name, class_icon_id, object_icon_id, table_name, primary_key_field, indexed, array_link, policy) VALUES ('test6', 1, 1, 'test6', 'ID', false, false, (select id from cs_policy where name like 'WIKI'));

INSERT INTO cs_type(name, class_id, complex_type) VALUES ('test1', (select id from cs_class where name like 'test1'), true);
INSERT INTO cs_type(name, class_id, complex_type) VALUES ('test2', (select id from cs_class where name like 'test2'), true);
INSERT INTO cs_type(name, class_id, complex_type) VALUES ('test3', (select id from cs_class where name like 'test3'), true);
INSERT INTO cs_type(name, class_id, complex_type) VALUES ('test4', (select id from cs_class where name like 'test4'), true);
INSERT INTO cs_type(name, class_id, complex_type) VALUES ('test5', (select id from cs_class where name like 'test5'), true);
INSERT INTO cs_type(name, class_id, complex_type) VALUES ('test6', (select id from cs_class where name like 'test6'), true);

INSERT INTO cs_attr(class_id, type_id, name, field_name, foreign_key, substitute, visible, indexed, isarray, optional, extension_attr) VALUES ((select id from cs_class where name like 'test1'), (select id from cs_type where name ilike 'integer'), 'id', 'id', false, false, false, false, false, false,  false);
INSERT INTO cs_attr(class_id, type_id, name, field_name, foreign_key, substitute, visible, indexed, isarray, optional, extension_attr) VALUES ((select id from cs_class where name like 'test1'), (select id from cs_type where name ilike 'varchar'), 'name', 'name', false, false, false, false, false, false,  false);
INSERT INTO cs_attr(class_id, type_id, name, field_name, foreign_key, substitute, visible, indexed, isarray, optional, extension_attr) VALUES ((select id from cs_class where name like 'test2'), (select id from cs_type where name ilike 'integer'), 'id', 'id', false, false, false, false, false, false,  false);
INSERT INTO cs_attr(class_id, type_id, name, field_name, foreign_key, substitute, visible, indexed, isarray, optional, extension_attr) VALUES ((select id from cs_class where name like 'test2'), (select id from cs_type where name ilike 'varchar'), 'name', 'name', false, false, false, false, false, false,  false);
INSERT INTO cs_attr(class_id, type_id, name, field_name, foreign_key, substitute, visible, indexed, isarray, optional, extension_attr) VALUES ((select id from cs_class where name like 'test3'), (select id from cs_type where name ilike 'integer'), 'id', 'id', false, false, false, false, false, false,  false);
INSERT INTO cs_attr(class_id, type_id, name, field_name, foreign_key, substitute, visible, indexed, isarray, optional, extension_attr) VALUES ((select id from cs_class where name like 'test3'), (select id from cs_type where name ilike 'varchar'), 'name', 'name', false, false, false, false, false, false,  false);
INSERT INTO cs_attr(class_id, type_id, name, field_name, foreign_key, substitute, visible, indexed, isarray, optional, extension_attr) VALUES ((select id from cs_class where name like 'test4'), (select id from cs_type where name ilike 'integer'), 'id', 'id', false, false, false, false, false, false,  false);
INSERT INTO cs_attr(class_id, type_id, name, field_name, foreign_key, substitute, visible, indexed, isarray, optional, extension_attr) VALUES ((select id from cs_class where name like 'test4'), (select id from cs_type where name ilike 'varchar'), 'name', 'name', false, false, false, false, false, false,  false);
INSERT INTO cs_attr(class_id, type_id, name, field_name, foreign_key, substitute, visible, indexed, isarray, optional, extension_attr) VALUES ((select id from cs_class where name like 'test5'), (select id from cs_type where name ilike 'integer'), 'id', 'id', false, false, false, false, false, false,  false);
INSERT INTO cs_attr(class_id, type_id, name, field_name, foreign_key, substitute, visible, indexed, isarray, optional, extension_attr) VALUES ((select id from cs_class where name like 'test5'), (select id from cs_type where name ilike 'varchar'), 'name', 'name', false, false, false, false, false, false,  false);
INSERT INTO cs_attr(class_id, type_id, name, field_name, foreign_key, substitute, visible, indexed, isarray, optional, extension_attr) VALUES ((select id from cs_class where name like 'test6'), (select id from cs_type where name ilike 'integer'), 'id', 'id', false, false, false, false, false, false,  false);
INSERT INTO cs_attr(class_id, type_id, name, field_name, foreign_key, substitute, visible, indexed, isarray, optional, extension_attr) VALUES ((select id from cs_class where name like 'test6'), (select id from cs_type where name ilike 'varchar'), 'name', 'name', false, false, false, false, false, false,  false);

INSERT INTO cs_class_attr(class_id, type_id, attr_key, attr_value) VALUES ((select id from cs_class where name like 'test2'), (select id from cs_type where name ilike 'varchar'), 'history_enabled', null);
INSERT INTO cs_class_attr(class_id, type_id, attr_key, attr_value) VALUES ((select id from cs_class where name like 'test3'), (select id from cs_type where name ilike 'varchar'), 'history_enabled', 'anonymous=true');
INSERT INTO cs_class_attr(class_id, type_id, attr_key, attr_value) VALUES ((select id from cs_class where name like 'test4'), (select id from cs_type where name ilike 'varchar'), 'history_enabled', '');
INSERT INTO cs_class_attr(class_id, type_id, attr_key, attr_value) VALUES ((select id from cs_class where name like 'test6'), (select id from cs_type where name ilike 'varchar'), 'history_enabled', 'anonymous=true');
